language: c

script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON .. || exit $?
  - make VERBOSE=1 || exit $?
  - cd ../fixtures && ../build/hessian_test || exit $?
  - ../build/encode
  - ../build/decode
  - nvm install 7.8.0 && nvm use 7.8.0
  - git clone https://github.com/node-modules/hessian.js.git && cd hessian.js && npm install && npm run benchmark
