language: c

script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON .. || exit $?
  - make VERBOSE=1 || exit $?
  - cd ../fixtures && ../build/hessian_test || exit $?
